# Generated by Django 4.2.1 on 2023-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount', models.CharField(default=0, max_length=10)),
                ('duration', models.FloatField()),
                ('authorname', models.CharField(max_length=100)),
            ],
        ),
    ]
